// Curated list of well-known corporate domains genuinely active in India,
// pre-approved as companies. Plain JS (not .ts) so it can be imported both by
// scripts/seed-company-domains.mjs (run with plain `node`) and by the Next.js
// cron route app/api/cron/company-domains-sync.
//
// This is the static half of company coverage. The other half is the
// CompanyRequest queue, auto-filed whenever a real user signs up with a
// corporate domain not on this list — reviewed at /admin/companies.

export const COMPANY_DOMAINS = [
  // ── IT Services / ITES ──────────────────────────────────────────────────
  ["Tata Consultancy Services", "tcs.com"],
  ["Infosys", "infosys.com"],
  ["Wipro", "wipro.com"],
  ["HCLTech", "hcltech.com"],
  ["Tech Mahindra", "techmahindra.com"],
  ["LTIMindtree", "ltimindtree.com"],
  ["Cognizant", "cognizant.com"],
  ["Accenture", "accenture.com"],
  ["Capgemini", "capgemini.com"],
  ["IBM", "ibm.com"],
  ["Genpact", "genpact.com"],
  ["WNS Global Services", "wns.com"],
  ["Mphasis", "mphasis.com"],
  ["Persistent Systems", "persistent.com"],
  ["Hexaware Technologies", "hexaware.com"],
  ["Cyient", "cyient.com"],
  ["Zensar Technologies", "zensar.com"],
  ["Larsen & Toubro Infotech", "lntinfotech.com"],
  ["Mindtree", "mindtree.com"],
  ["Birlasoft", "birlasoft.com"],
  ["Sonata Software", "sonata-software.com"],
  ["NIIT Technologies", "niit-tech.com"],
  ["DXC Technology", "dxc.com"],
  ["Oracle", "oracle.com"],
  ["SAP", "sap.com"],
  ["Microsoft", "microsoft.com"],
  ["Google", "google.com"],
  ["Amazon", "amazon.com"],
  ["Adobe", "adobe.com"],
  ["Salesforce", "salesforce.com"],
  ["Dell Technologies", "dell.com"],
  ["HP", "hp.com"],
  ["Cisco", "cisco.com"],
  ["Intel", "intel.com"],
  ["Qualcomm", "qualcomm.com"],
  ["Samsung", "samsung.com"],
  ["ServiceNow", "servicenow.com"],
  ["VMware", "vmware.com"],
  ["Nvidia", "nvidia.com"],
  ["AMD", "amd.com"],
  ["Ericsson", "ericsson.com"],
  ["Nokia", "nokia.com"],
  ["Juniper Networks", "juniper.net"],
  ["Freshworks", "freshworks.com"],
  ["Zoho", "zohocorp.com"],

  // ── Banking / Financial Services ────────────────────────────────────────
  ["HDFC Bank", "hdfcbank.com"],
  ["ICICI Bank", "icicibank.com"],
  ["Axis Bank", "axisbank.com"],
  ["Kotak Mahindra Bank", "kotak.com"],
  ["State Bank of India", "sbi.co.in"],
  ["IndusInd Bank", "indusind.com"],
  ["Punjab National Bank", "pnbindia.in"],
  ["Bank of Baroda", "bankofbaroda.in"],
  ["Canara Bank", "canarabank.com"],
  ["IDFC First Bank", "idfcfirstbank.com"],
  ["Federal Bank", "federalbank.co.in"],
  ["RBL Bank", "rblbank.com"],
  ["Yes Bank", "yesbank.in"],
  ["Bajaj Finserv", "bajajfinserv.in"],
  ["HDFC Life", "hdfclife.com"],
  ["ICICI Prudential Life Insurance", "iciciprulife.com"],
  ["SBI Life Insurance", "sbilife.co.in"],
  ["LIC of India", "licindia.in"],
  ["HDFC ERGO", "hdfcergo.com"],
  ["Policybazaar", "policybazaar.com"],
  ["Paytm", "paytm.com"],
  ["PhonePe", "phonepe.com"],
  ["Razorpay", "razorpay.com"],
  ["Cred", "cred.club"],
  ["Groww", "groww.in"],
  ["Zerodha", "zerodha.com"],
  ["Upstox", "upstox.com"],
  ["Angel One", "angelone.in"],
  ["Motilal Oswal", "motilaloswal.com"],
  ["JPMorgan Chase", "jpmorgan.com"],
  ["Morgan Stanley", "morganstanley.com"],
  ["Goldman Sachs", "gs.com"],
  ["Barclays", "barclays.com"],
  ["HSBC", "hsbc.co.in"],
  ["Standard Chartered", "sc.com"],
  ["Citi", "citi.com"],
  ["Deutsche Bank", "db.com"],
  ["American Express", "aexp.com"],
  ["Mastercard", "mastercard.com"],
  ["Visa", "visa.com"],
  ["PayPal", "paypal.com"],

  // ── Consulting / Professional Services ──────────────────────────────────
  ["EY (Ernst & Young)", "ey.com"],
  ["Deloitte", "deloitte.com"],
  ["KPMG", "kpmg.com"],
  ["PwC", "pwc.com"],
  ["McKinsey & Company", "mckinsey.com"],
  ["Boston Consulting Group", "bcg.com"],
  ["Bain & Company", "bain.com"],

  // ── Conglomerates / Industrial / Auto ───────────────────────────────────
  ["Reliance Industries", "ril.com"],
  ["Tata Motors", "tatamotors.com"],
  ["Tata Steel", "tatasteel.com"],
  ["Tata Power", "tatapower.com"],
  ["Tata Chemicals", "tatachemicals.com"],
  ["Aditya Birla Group", "adityabirla.com"],
  ["Mahindra Group", "mahindra.com"],
  ["Bajaj Auto", "bajajauto.com"],
  ["Maruti Suzuki", "maruti.co.in"],
  ["Hyundai Motor India", "hyundai.com"],
  ["Honda Cars India", "hondacarindia.com"],
  ["Larsen & Toubro", "larsentoubro.com"],
  ["Godrej Group", "godrej.com"],
  ["Godrej Consumer Products", "godrejcp.com"],
  ["Siemens", "siemens.com"],
  ["Honeywell", "honeywell.com"],
  ["General Electric", "ge.com"],
  ["ABB", "abb.com"],
  ["Schneider Electric", "se.com"],
  ["JSW Group", "jsw.in"],
  ["Adani Group", "adani.com"],
  ["Vedanta", "vedantaresources.com"],
  ["Hindustan Zinc", "hzlindia.com"],

  // ── FMCG / Consumer ──────────────────────────────────────────────────────
  ["Hindustan Unilever", "hul.co.in"],
  ["ITC Limited", "itcportal.com"],
  ["Nestle India", "nestle.in"],
  ["Britannia Industries", "britannia.co.in"],
  ["Dabur India", "dabur.com"],
  ["Marico", "marico.com"],
  ["Colgate-Palmolive India", "colgatepalmolive.co.in"],
  ["Procter & Gamble", "pg.com"],
  ["Pepsico India", "pepsico.com"],
  ["Coca-Cola India", "coca-colaindia.com"],

  // ── Pharma / Healthcare ──────────────────────────────────────────────────
  ["Cipla", "cipla.com"],
  ["Dr. Reddy's Laboratories", "drreddys.com"],
  ["Sun Pharmaceutical", "sunpharma.com"],
  ["Lupin", "lupin.com"],
  ["Aurobindo Pharma", "aurobindo.com"],
  ["Biocon", "biocon.com"],
  ["Zydus Lifesciences", "zyduslife.com"],
  ["Glenmark Pharmaceuticals", "glenmarkpharma.com"],
  ["Torrent Pharmaceuticals", "torrentpharma.com"],
  ["Apollo Hospitals", "apollohospitals.com"],
  ["Fortis Healthcare", "fortishealthcare.com"],
  ["Max Healthcare", "maxhealthcare.in"],

  // ── Telecom / Airlines ───────────────────────────────────────────────────
  ["Bharti Airtel", "airtel.in"],
  ["Reliance Jio", "jio.com"],
  ["Vodafone Idea", "vodafoneidea.com"],
  ["Tata Communications", "tatacommunications.com"],
  ["IndiGo", "goindigo.in"],
  ["Air India", "airindia.com"],
  ["SpiceJet", "spicejet.com"],
  ["Vistara", "airvistara.com"],

  // ── E-commerce / Internet / Startups ────────────────────────────────────
  ["Flipkart", "flipkart.com"],
  ["Myntra", "myntra.com"],
  ["Amazon India", "amazon.in"],
  ["Snapdeal", "snapdeal.com"],
  ["Meesho", "meesho.com"],
  ["Info Edge / Naukri.com", "naukri.com"],
  ["Swiggy", "swiggy.com"],
  ["Zomato", "zomato.com"],
  ["BYJU'S", "byjus.com"],
  ["Unacademy", "unacademy.com"],
  ["upGrad", "upgrad.com"],
  ["Ola", "olacabs.com"],
  ["Uber India", "uber.com"],
  ["Cars24", "cars24.com"],
  ["Urban Company", "urbancompany.com"],
  ["Lenskart", "lenskart.com"],
  ["Nykaa", "nykaa.com"],
  ["FirstCry", "firstcry.com"],
  ["BigBasket", "bigbasket.com"],
  ["OYO Rooms", "oyorooms.com"],
  ["MakeMyTrip", "makemytrip.com"],
  ["Goibibo", "goibibo.com"],
  ["Cleartrip", "cleartrip.com"],
  ["ixigo", "ixigo.com"],
  ["redBus", "redbus.in"],
  ["Dream11", "dream11.com"],
]
