export interface ServiceConfig {
  id: string
  name: string
  icon: string
  description: string
  color: string
  bgColor: string
  borderColor: string
  route: string
  model: string
  isPremium: boolean
  isActive: boolean
  badge?: string
}

export const SERVICES: ServiceConfig[] = [
  {
    id: "buy-sell",
    name: "Buy & Sell",
    icon: "ShoppingBag",
    description: "Buy and sell electronics, vehicles, furniture and more with verified colleagues",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-100 dark:bg-blue-500/15",
    borderColor: "border-blue-200 dark:border-blue-800",
    route: "/marketplace",
    model: "Listing",
    isPremium: false,
    isActive: true,
    badge: "Popular",
  },
  {
    id: "rentals",
    name: "Rental & Flatmate Hub",
    icon: "Home",
    description: "Find verified apartments, PGs, rooms and flatmates near your office",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-100 dark:bg-emerald-500/15",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    route: "/rentals",
    model: "RentalPost",
    isPremium: false,
    isActive: true,
  },
  {
    id: "job-referrals",
    name: "Job Referrals",
    icon: "Briefcase",
    description: "Post and find internal referrals within trusted corporate networks",
    color: "text-violet-600 dark:text-violet-400",
    bgColor: "bg-violet-100 dark:bg-violet-500/15",
    borderColor: "border-violet-200 dark:border-violet-800",
    route: "/referrals",
    model: "JobReferral",
    isPremium: false,
    isActive: true,
  },
  {
    id: "carpool",
    name: "Corporate Carpool",
    icon: "Car",
    description: "Share your daily commute with verified colleagues on the same route",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-100 dark:bg-orange-500/15",
    borderColor: "border-orange-200 dark:border-orange-800",
    route: "/carpool",
    model: "CarpoolRoute",
    isPremium: false,
    isActive: true,
  },
  {
    id: "services",
    name: "Skill Marketplace",
    icon: "Wrench",
    description: "Hire verified professionals for photography, coding, design, tax filing and more",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-100 dark:bg-cyan-500/15",
    borderColor: "border-cyan-200 dark:border-cyan-800",
    route: "/services",
    model: "ServicePost",
    isPremium: false,
    isActive: true,
  },
  {
    id: "deals",
    name: "Employee Deals",
    icon: "Tag",
    description: "Exclusive discounts from curated brands — only for verified corporate employees",
    color: "text-rose-600 dark:text-rose-400",
    bgColor: "bg-rose-100 dark:bg-rose-500/15",
    borderColor: "border-rose-200 dark:border-rose-800",
    route: "/deals",
    model: "Deal",
    isPremium: false,
    isActive: false,
  },
  {
    id: "events",
    name: "Events & Communities",
    icon: "Users",
    description: "Join treks, sports groups, networking events and hobby communities",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-100 dark:bg-amber-500/15",
    borderColor: "border-amber-200 dark:border-amber-800",
    route: "/events",
    model: "Event",
    isPremium: false,
    isActive: true,
  },
  {
    id: "learning",
    name: "Learning Hub",
    icon: "GraduationCap",
    description: "Workshops, mentoring and certification prep from peer professionals",
    color: "text-indigo-600 dark:text-indigo-400",
    bgColor: "bg-indigo-100 dark:bg-indigo-500/15",
    borderColor: "border-indigo-200 dark:border-indigo-800",
    route: "/learning",
    model: "Course",
    isPremium: false,
    isActive: false,
  },
  {
    id: "concierge",
    name: "Concierge Services",
    icon: "Shield",
    description: "Tax, legal, insurance and financial guidance from vetted professionals",
    color: "text-sky-600 dark:text-sky-400",
    bgColor: "bg-sky-100 dark:bg-sky-500/15",
    borderColor: "border-sky-200 dark:border-sky-800",
    route: "/concierge",
    model: "ConciergeLead",
    isPremium: false,
    isActive: false,
  },
  {
    id: "benefits",
    name: "Employee Benefits",
    icon: "Gift",
    description: "Loans, insurance, travel packages and financial products for salaried professionals",
    color: "text-pink-600 dark:text-pink-400",
    bgColor: "bg-pink-100 dark:bg-pink-500/15",
    borderColor: "border-pink-200 dark:border-pink-800",
    route: "/benefits",
    model: "BenefitProduct",
    isPremium: false,
    isActive: false,
  },
]

export { INDIAN_CITIES as CITIES } from "@/data/indian-cities"

export const FREE_SERVICES = SERVICES.filter((s) => !s.isPremium)
export const PREMIUM_SERVICES = SERVICES.filter((s) => s.isPremium)
export const ACTIVE_SERVICES = SERVICES.filter((s) => s.isActive)

// ─── Marketplace ──────────────────────────────────────────────────────────────

export const LISTING_CATEGORIES = [
  {
    value: "ELECTRONICS", label: "Electronics", icon: "Cpu",
    subcategories: [
      "Mobile Phones", "Smartphones - Android", "Smartphones - iPhone",
      "Laptops", "MacBooks", "Gaming Laptops", "Ultrabooks & Thin Laptops",
      "Tablets", "iPads", "Android Tablets",
      "Desktops & All-in-Ones", "Computer Components - CPU", "Computer Components - GPU",
      "Computer Components - RAM", "Computer Components - Motherboard", "Computer Components - SSD & HDD",
      "Monitors", "Keyboards & Mice", "Webcams & Microphones",
      "Printers & Scanners", "Networking - Routers & Modems", "External Storage & Pen Drives",
      "Cameras - DSLR", "Cameras - Mirrorless", "Cameras - Action & GoPro", "Lenses & Camera Accessories",
      "Headphones & Earphones", "Bluetooth Speakers", "Soundbars & Home Theatre",
      "Smartwatches", "Fitness Bands", "Smart TVs", "Projectors",
      "Gaming Consoles - PlayStation", "Gaming Consoles - Xbox", "Gaming Consoles - Nintendo",
      "Gaming Accessories - Controllers", "Gaming Accessories - Headsets",
      "Smart Home - Speakers", "Smart Home - Bulbs & Switches", "Smart Home - CCTV & Security",
      "Drones & RC Toys", "E-Readers", "Power Banks & Chargers",
      "Phone Accessories - Cases & Covers", "Phone Accessories - Screen Guards",
      "Cables & Adapters", "UPS & Inverters", "Other Electronics",
    ],
  },
  {
    value: "VEHICLE", label: "Vehicles", icon: "Car",
    subcategories: [
      "Cars - Hatchback", "Cars - Sedan", "Cars - SUV", "Cars - MUV & Van",
      "Cars - Luxury", "Cars - Sports", "Cars - Electric",
      "Motorcycles - Commuter", "Motorcycles - Sports & Performance", "Motorcycles - Cruiser",
      "Motorcycles - Adventure & Touring", "Motorcycles - Electric",
      "Scooters & Mopeds", "Electric Scooters",
      "Auto Parts - Engine & Transmission", "Auto Parts - Brakes & Suspension",
      "Auto Parts - Body Parts & Panels", "Auto Parts - Electrical & Lighting",
      "Tyres & Alloy Wheels", "Car Audio & Infotainment",
      "Car Accessories - Seat Covers", "Car Accessories - Dash Cams",
      "Car Accessories - Car Care & Cleaning", "Helmets & Riding Gear",
      "Bike Parts & Accessories", "Number Plates & Documents",
      "Commercial Vehicles - Trucks", "Commercial Vehicles - Auto Rickshaws",
      "Other Vehicles",
    ],
  },
  {
    value: "FURNITURE", label: "Furniture", icon: "Armchair",
    subcategories: [
      "Sofas - 2 Seater", "Sofas - 3 Seater", "Sofas - L-Shaped / Corner",
      "Recliners", "Bean Bags & Floor Seating",
      "Beds - Single", "Beds - Double / Queen / King", "Bunk Beds",
      "Mattresses - Memory Foam", "Mattresses - Spring", "Mattresses - Orthopaedic",
      "Pillows & Bed Accessories",
      "Dining Tables", "Dining Chairs", "Bar Stools",
      "Coffee Tables", "Side & End Tables", "Console Tables",
      "Study & Work Desks", "Bookshelves & Display Units",
      "Wardrobes - Sliding Door", "Wardrobes - Swing Door",
      "Dressers & Chest of Drawers", "TV Units & Entertainment Centres",
      "Shoe Racks", "Coat Stands & Hooks",
      "Bathroom Furniture", "Garden & Outdoor Furniture",
      "Office Chairs", "Office Desks & Workstations",
      "Kids' Furniture", "Other Furniture",
    ],
  },
  {
    value: "APPLIANCE", label: "Appliances", icon: "Tv",
    subcategories: [
      "Refrigerators - Single Door", "Refrigerators - Double Door",
      "Refrigerators - Side-by-Side", "Refrigerators - French Door",
      "Washing Machines - Front Load", "Washing Machines - Top Load",
      "Washing Machines - Semi-Automatic", "Dryers",
      "Air Conditioners - Split", "Air Conditioners - Window", "Air Conditioners - Portable",
      "Microwaves - Solo", "Microwaves - Convection & Grill", "OTG Ovens",
      "Chimneys & Kitchen Hoods", "Dishwashers",
      "Water Purifiers & RO Systems", "Geysers & Water Heaters",
      "Air Purifiers", "Humidifiers & Dehumidifiers",
      "Vacuum Cleaners - Upright", "Vacuum Cleaners - Robot",
      "Irons & Garment Steamers", "Sewing Machines",
      "Ceiling Fans", "Table Fans & Pedestal Fans", "Exhaust Fans",
      "Inverters & Stabilisers", "Other Appliances",
    ],
  },
  {
    value: "BOOKS", label: "Books", icon: "BookOpen",
    subcategories: [
      "Engineering - Computer Science", "Engineering - Mechanical", "Engineering - Civil",
      "Engineering - Electronics", "Medical & Nursing", "Pharmacy",
      "MBA & Management", "CA & Finance", "Law & LLB",
      "Science - Physics", "Science - Chemistry", "Science - Biology", "Maths",
      "Arts & Humanities", "Social Sciences",
      "Fiction - Literary", "Fiction - Mystery & Thriller", "Fiction - Romance",
      "Fiction - Sci-Fi & Fantasy", "Fiction - Horror",
      "Non-Fiction - Biography & Memoir", "Non-Fiction - History & Politics",
      "Self Help & Personal Development", "Business & Entrepreneurship",
      "Health & Wellness", "Spirituality & Philosophy",
      "Travel & Adventure", "Cookbooks & Food",
      "Parenting & Family", "Children's - Picture Books", "Children's - Middle Grade",
      "Comics - Marvel & DC", "Comics - Manga & Anime", "Graphic Novels",
      "Competitive Exams - UPSC & IAS", "Competitive Exams - JEE & NEET",
      "Competitive Exams - CAT & MBA", "Competitive Exams - SSC & Banking",
      "Competitive Exams - GATE", "Magazines & Journals", "Other Books",
    ],
  },
  {
    value: "SPORTS", label: "Sports & Fitness", icon: "Dumbbell",
    subcategories: [
      "Treadmills", "Ellipticals & Cross Trainers", "Exercise & Spin Bikes",
      "Rowing Machines", "Dumbbells & Barbells", "Weight Plates & Discs",
      "Benches & Squat Racks", "Pull-Up Bars & Dip Stations",
      "Resistance Bands & Tubes", "Gym Mats & Flooring",
      "Foam Rollers & Massage Tools",
      "Yoga Mats", "Yoga Props & Blocks", "Pilates Equipment",
      "Cricket - Bats", "Cricket - Helmets & Pads", "Cricket - Balls & Kits",
      "Football - Balls & Gear", "Basketball - Balls & Hoops",
      "Badminton - Rackets & Shuttles", "Tennis - Rackets & Balls",
      "Table Tennis - Tables & Bats",
      "Swimming - Goggles & Caps", "Swimming - Fins & Kickboards",
      "Cycling - Helmets & Gloves", "Cycling - Water Bottles & Cages",
      "Boxing & MMA Equipment", "Martial Arts - Gi & Uniforms",
      "Golf - Clubs & Bags", "Golf - Balls & Accessories",
      "Skating & Skateboarding", "Rock Climbing & Rappelling",
      "Trekking - Boots & Shoes", "Trekking - Backpacks & Gear",
      "Outdoor & Camping Equipment", "Sports Nutrition",
      "Sportswear & Jerseys", "Other Sports",
    ],
  },
  {
    value: "CLOTHING", label: "Clothing & Fashion", icon: "Shirt",
    subcategories: [
      "Men's T-Shirts & Polos", "Men's Casual Shirts", "Men's Formal Shirts",
      "Men's Trousers & Chinos", "Men's Jeans", "Men's Suits & Blazers",
      "Men's Traditional - Kurtas & Sherwanis", "Men's Ethnic Sets",
      "Men's Jackets & Coats", "Men's Hoodies & Sweatshirts",
      "Men's Sportswear & Track Suits", "Men's Innerwear & Loungewear",
      "Women's Kurtas & Salwar Suits", "Women's Sarees", "Women's Lehengas",
      "Women's Western - Tops & Blouses", "Women's Dresses & Jumpsuits",
      "Women's Trousers & Jeans", "Women's Skirts",
      "Women's Jackets, Shrugs & Cardigans", "Women's Sportswear & Yoga Wear",
      "Women's Innerwear & Lingerie",
      "Kids' Boys Clothing", "Kids' Girls Clothing",
      "School Uniforms", "Infant & Baby Clothing (0–2 yrs)",
      "Footwear - Men's Formal Shoes", "Footwear - Men's Casual & Sneakers",
      "Footwear - Women's Heels & Flats", "Footwear - Women's Sandals",
      "Footwear - Sports & Running Shoes", "Footwear - Kids'",
      "Handbags & Purses", "Backpacks & Laptop Bags", "Wallets & Belts",
      "Watches - Men's", "Watches - Women's",
      "Sunglasses", "Jewellery - Necklaces", "Jewellery - Earrings",
      "Jewellery - Bracelets & Rings",
      "Caps, Hats & Scarves", "Other Clothing & Accessories",
    ],
  },
  {
    value: "KITCHEN", label: "Kitchen", icon: "UtensilsCrossed",
    subcategories: [
      "Cookware - Non-Stick Pans & Kadai", "Cookware - Stainless Steel",
      "Cookware - Cast Iron", "Pressure Cookers",
      "Mixer Grinders", "Juicers & Blenders", "Food Processors",
      "Electric Kettles", "Toasters & Sandwich Makers", "Air Fryers",
      "Induction & Hot Plates", "Rice Cookers & Steamers",
      "Coffee & Tea Makers", "Oven Toaster Grills (OTG)",
      "Crockery & Dinner Sets", "Glasses, Mugs & Cups",
      "Cutlery & Serving Spoons", "Lunch Boxes & Tiffins",
      "Water Bottles & Flasks", "Food Storage Containers",
      "Chopping Boards & Knife Sets", "Peelers & Graters",
      "Baking Moulds & Accessories", "Kitchen Weighing Scales",
      "Kitchen Organizers & Racks", "Aprons & Kitchen Linens",
      "Cleaning & Scrubbers", "Other Kitchen Items",
    ],
  },
  {
    value: "OFFICE", label: "Office & Stationery", icon: "Briefcase",
    subcategories: [
      "Office Chairs - Ergonomic", "Office Chairs - Executive",
      "Office Chairs - Mesh", "Standing Desks & Converters",
      "L-Shaped & Corner Desks", "Straight Desks",
      "Pedestals & Filing Cabinets", "Lockers & Storage Shelves",
      "Whiteboards & Flip Charts", "Pinboards & Notice Boards",
      "Projectors & Presentation Screens",
      "Shredders", "Laminators", "Binding Machines",
      "Label Makers & Staplers",
      "Pens & Markers - Gel & Ballpoint", "Pens - Premium & Fountain",
      "Notebooks & Notepads", "Planners & Diaries",
      "Files, Folders & Binders", "Desk Organisers & Trays",
      "Printer Ink & Toner Cartridges",
      "Keyboard & Mouse Sets", "Monitor Arms & Stands",
      "Laptop Stands & Docking Stations",
      "Webcams & Conference Equipment", "Other Office Items",
    ],
  },
  {
    value: "BICYCLE", label: "Bicycles", icon: "Bike",
    subcategories: [
      "Mountain Bikes - Hardtail", "Mountain Bikes - Full Suspension",
      "Road Bikes", "Gravel & Adventure Bikes",
      "Hybrid & City Bikes", "Folding Bikes",
      "Electric Bicycles (eBikes)", "Electric Folding Bikes",
      "Kids' Bicycles - 12\" & 14\"", "Kids' Bicycles - 16\" & 20\"",
      "Junior Bikes - 24\"", "BMX Bikes", "Fixie & Single Speed",
      "Frames & Forks", "Wheels & Tyres",
      "Groupsets - Shimano", "Groupsets - SRAM",
      "Drivetrains - Chains & Cassettes", "Brakes - Disc & Rim",
      "Saddles & Seatposts", "Handlebars & Stems",
      "Pedals & Cleats", "Cycling Computers & GPS",
      "Lights - Front & Rear", "Helmets - Road", "Helmets - MTB",
      "Gloves & Arm Warmers", "Cycling Shorts & Jerseys",
      "Panniers & Bike Bags", "Racks & Mudguards",
      "Bike Locks & Security", "Bike Maintenance Tools",
      "Other Bicycle Items",
    ],
  },
  {
    value: "HEALTH", label: "Health & Medical", icon: "Activity",
    subcategories: [
      "Home Gym Equipment", "Dumbbells & Kettlebells",
      "Pull-Up Bars & Rings", "Resistance Bands",
      "Foam Rollers & Massage Guns", "Ab Rollers & Core Trainers",
      "Protein Supplements - Whey", "Protein Supplements - Plant Based",
      "Creatine & Pre-Workout", "Vitamins & Minerals",
      "Ayurvedic & Herbal Products", "Homeopathy Products",
      "Blood Pressure Monitors", "Glucometers & Lancets",
      "Pulse Oximeters", "Digital Thermometers",
      "Nebulizers & Inhalers", "CPAP & Sleep Apnea",
      "Orthopedic Supports - Knee & Ankle",
      "Orthopedic Supports - Back & Lumbar",
      "Orthopedic Supports - Wrist & Elbow",
      "Crutches & Walking Sticks",
      "Wheelchairs - Manual", "Wheelchairs - Electric",
      "Hospital Beds & Patient Aids",
      "Hearing Aids", "Eyeglasses & Spectacles",
      "Surgical & Medical Instruments",
      "Personal Protective Equipment (PPE)",
      "Sanitary & Hygiene Products",
      "Massagers & Physiotherapy Devices",
      "Other Health Items",
    ],
  },
  {
    value: "HOME_DECOR", label: "Home Décor", icon: "Palette",
    subcategories: [
      "Wall Paintings - Abstract", "Wall Paintings - Landscape",
      "Wall Paintings - Religious & Spiritual",
      "Photo Frames & Collages", "Canvases & Posters",
      "Wall Clocks - Analog", "Wall Clocks - Digital",
      "Mirrors - Full Length", "Mirrors - Decorative",
      "Ceiling Lights & Chandeliers", "Pendant & Hanging Lights",
      "Floor Lamps & Reading Lamps", "Table Lamps",
      "String Lights & Fairy Lights", "LED Strips & Night Lights",
      "Indoor Plants - Low Maintenance",
      "Indoor Plants - Succulents & Cacti",
      "Ceramic & Terracotta Pots", "Hanging Planters",
      "Artificial Plants & Flowers",
      "Rugs - Woollen", "Rugs - Cotton", "Rugs - Geometric & Modern",
      "Door Mats & Kitchen Mats",
      "Cushions & Cushion Covers", "Throws & Blankets",
      "Curtains - Blackout", "Curtains - Sheer & Linen",
      "Blinds - Roller & Roman",
      "Candles & Diffusers", "Incense & Aromatherapy",
      "Vases & Flower Pots", "Figurines & Decorative Objects",
      "Clocks & Showpieces",
      "Bathroom Décor & Accessories",
      "Kitchen Décor - Printed Tiles & Boards",
      "Festival & Seasonal Décor", "Other Décor",
    ],
  },
  {
    value: "TICKETS", label: "Tickets & Passes", icon: "Ticket",
    subcategories: [
      "Cricket - IPL Matches", "Cricket - International (Test/ODI/T20)",
      "Football - ISL Matches", "Football - International",
      "Kabaddi - PKL Matches", "Basketball - NBA India",
      "Other Sports Events",
      "Bollywood Concerts", "International Artist Concerts",
      "Music Festivals", "Classical Music Concerts",
      "Stand-Up Comedy Shows", "Theatre & Drama Plays",
      "Dance Performances - Classical", "Dance Performances - Contemporary",
      "Opera & Symphony", "Film Premieres & Screenings",
      "Film Festivals", "OTT & Streaming Subscriptions",
      "Tech Conferences & Summits", "Startup & Business Events",
      "Industry Seminars & Expos", "Art Exhibitions & Galleries",
      "Food & Culinary Festivals", "Gaming Tournaments & Esports",
      "Workshops - Photography", "Workshops - Art & Craft",
      "Workshops - Cooking & Baking", "Workshops - Fitness & Yoga",
      "Masterclasses & Online Courses",
      "Amusement Parks & Theme Parks",
      "Adventure Activities - Trekking & Camping",
      "Adventure Activities - Water Sports",
      "Travel Packages - Domestic", "Travel Packages - International",
      "Holiday & Tour Packages",
      "Annual Passes & Memberships",
      "Gym & Fitness Memberships",
      "Club & Lounge Memberships",
      "Other Tickets & Passes",
    ],
  },
  {
    value: "OTHER", label: "Other Items", icon: "Package",
    subcategories: [
      "Toys - Educational & STEM", "Toys - Action Figures & Dolls",
      "Toys - Remote Control Cars & Drones",
      "Board Games & Card Games", "Jigsaw Puzzles",
      "Video Games - PS5 Games", "Video Games - Xbox Games",
      "Video Games - PC / Steam Games", "Video Games - Nintendo Switch",
      "Musical Instruments - Guitars - Acoustic",
      "Musical Instruments - Guitars - Electric",
      "Musical Instruments - Keyboards & Synthesizers",
      "Musical Instruments - Drums & Percussion",
      "Musical Instruments - Violin & String",
      "Musical Instruments - Flute & Wind",
      "Musical Instruments - Harmonium & Indian Classical",
      "Art Supplies - Canvas & Brushes",
      "Art Supplies - Watercolours & Acrylics",
      "Art Supplies - Sketching & Drawing",
      "Craft & DIY Kits",
      "Pet Accessories - Dogs", "Pet Accessories - Cats",
      "Pet Food & Nutrition", "Aquarium & Fish Accessories",
      "Baby Strollers & Prams", "Baby Car Seats",
      "Baby Carriers & Swings", "Baby Monitors",
      "Infant Feeding Products",
      "Stamps, Coins & Philatelic Collectibles",
      "Antiques & Vintage Items",
      "Trading Cards - Pokémon & Others",
      "Action Figures & Memorabilia",
      "Hand Tools - Hammer, Wrench & Screwdrivers",
      "Power Tools - Drills & Saws",
      "Ladders & Safety Equipment",
      "Gardening Tools & Equipment",
      "Seeds, Soil & Fertilisers",
      "Religious & Puja Items",
      "Luggage & Travel Accessories",
      "Miscellaneous Items",
    ],
  },
]

export const LISTING_CONDITIONS = [
  { value: "NEW",       label: "Brand New",   badge: "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300 border-green-200 dark:border-green-700" },
  { value: "LIKE_NEW",  label: "Like New",    badge: "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-700" },
  { value: "GOOD",      label: "Good",        badge: "bg-yellow-100 dark:bg-yellow-900/40 text-yellow-700 dark:text-yellow-300 border-yellow-200 dark:border-yellow-700" },
  { value: "FAIR",      label: "Fair",        badge: "bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-700" },
  { value: "POOR",      label: "For Parts",   badge: "bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300 border-red-200 dark:border-red-700" },
] as const

export const BOOST_TIERS = [
  {
    level:        "BASIC",
    label:        "Basic Boost",
    price:        4900,    // paise
    displayPrice: 49,
    days:         7,
    icon:         "🚀",
    description:  "Rise above regular listings in search & category views",
    cardClass:    "border-blue-200 dark:border-blue-700 bg-blue-50/50 dark:bg-blue-900/20",
    badgeClass:   "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300",
    popular:      false,
  },
  {
    level:        "FEATURED",
    label:        "Featured",
    price:        9900,
    displayPrice: 99,
    days:         7,
    icon:         "⭐",
    description:  "Gold spotlight card in the Featured section + top of search results",
    cardClass:    "border-amber-300 dark:border-amber-600 bg-amber-50/50 dark:bg-amber-900/20",
    badgeClass:   "bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300",
    popular:      true,
  },
  {
    level:        "SUPER",
    label:        "Super Featured",
    price:        19900,
    displayPrice: 199,
    days:         14,
    icon:         "💥",
    description:  "Home page featured slot + top placement for 14 days — maximum exposure",
    cardClass:    "border-purple-300 dark:border-purple-600 bg-purple-50/50 dark:bg-purple-900/20",
    badgeClass:   "bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300",
    popular:      false,
  },
] as const

export type BoostLevel = "NONE" | "BASIC" | "FEATURED" | "SUPER"
export type ListingCondition = "NEW" | "LIKE_NEW" | "GOOD" | "FAIR" | "POOR" | "USED"
