/**
 * Seeds dummy events for all categories.
 * Run: & "C:\Program Files\nodejs\node.exe" --env-file=.env.local scripts/seed-events.mjs
 */

import { createClient } from "@libsql/client"

const db = createClient({
  url:       process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
})

const USERS = [
  "cmqaegcjk0000nwuwz3kvohry",  // Suman
  "cmqaeng0b0006nwuwf7llpxir",  // Lyra Suman
  "cmqdnhj9400116rxzwymg32l3",  // Charan Kumar
  "cmqcc7h6r00161098rlza1iiz",  // Charan
  "cmqaeu6ar000046rkynd9itly",  // Admin
]

function id()         { return "evt_" + Date.now() + "_" + Math.random().toString(36).slice(2, 9) }
function pick(arr)    { return arr[Math.floor(Math.random() * arr.length)] }
function daysFromNow(n) { return new Date(Date.now() + n * 86400_000).toISOString() }
function j(v)         { return JSON.stringify(v) }

const EVENTS = [

  // ── NETWORKING (3) ───────────────────────────────────────────────────────────
  {
    title:       "Corporate Networking Night — Bengaluru Tech Circle",
    description: "Join 100+ professionals from Bengaluru's leading tech companies for an evening of high-signal networking, lightning talks, and curated introductions.\n\nExpect structured rounds, a startup pitch corner, and a career-swap game that makes meeting strangers actually fun.\n\nDress code: Smart casual. Badge & LinkedIn QR mandatory.",
    category:    "NETWORKING",
    location:    "Taj MG Road, Bengaluru",
    date:        daysFromNow(5),
    fee:         499,
    maxParticipants: 120,
    images:      j(["https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80"]),
    tags:        j(["Tech", "Bengaluru", "Career", "Startup"]),
    agenda:      j([
      { time: "6:30 PM", title: "Doors open & registration", speaker: "" },
      { time: "7:00 PM", title: "Welcome note", speaker: "Suman M S" },
      { time: "7:15 PM", title: "Speed networking rounds (3 × 5 min)", speaker: "" },
      { time: "8:00 PM", title: "Lightning talks: Future of AI at work", speaker: "Panel" },
      { time: "8:45 PM", title: "Open networking & drinks", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[0],
  },
  {
    title:       "FinTech Leaders Breakfast Meet",
    description: "An intimate breakfast roundtable for senior professionals in banking, payments, and fintech. Limited to 25 seats.\n\nOpen discussion on CBDCs, embedded finance, and credit innovation in India. Seats are pre-approved — apply early.",
    category:    "NETWORKING",
    location:    "The Leela Palace, Bengaluru",
    date:        daysFromNow(8),
    fee:         0,
    maxParticipants: 25,
    images:      j(["https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200&q=80"]),
    tags:        j(["FinTech", "Banking", "Leaders"]),
    agenda:      null,
    isBoosted:   false,
    requiresApproval: true,
    organizerId: USERS[1],
  },
  {
    title:       "Women in Tech — Bengaluru Chapter Q3 Meetup",
    description: "Monthly gathering for women in engineering, product, and design. This edition: 'Navigating the AI era — skills, biases, and opportunities.'\n\nFeaturing talks from Google, Atlassian, and Meesho, followed by open mentoring sessions.",
    category:    "NETWORKING",
    location:    "WeWork Galaxy, Bengaluru",
    date:        daysFromNow(12),
    fee:         0,
    maxParticipants: 80,
    images:      j(["https://images.unsplash.com/photo-1573164574572-cb89e39749b4?w=1200&q=80"]),
    tags:        j(["Women in Tech", "Mentoring", "AI"]),
    agenda:      j([
      { time: "5:00 PM", title: "Registration & coffee", speaker: "" },
      { time: "5:30 PM", title: "Talk: AI tools that 10× your productivity", speaker: "Priya R, Google" },
      { time: "6:00 PM", title: "Talk: Building in public as a woman founder", speaker: "Ananya S, Meesho" },
      { time: "6:30 PM", title: "Open mentoring tables", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[2],
  },

  // ── TREK (3) ────────────────────────────────────────────────────────────────
  {
    title:       "Coorg Coffee Trail — Weekend Trek & Brew",
    description: "A 2-day trek through Coorg's aromatic coffee estates, forests, and waterfalls. End day 1 at a private estate homestay with a curated coffee tasting session.\n\nDifficulty: Easy-Moderate | Distance: ~14 km over 2 days\nIncludes: Transport from Bengaluru, meals, homestay, guide.",
    category:    "TREK",
    location:    "Coorg, Karnataka",
    date:        daysFromNow(14),
    fee:         3499,
    maxParticipants: 18,
    images:      j(["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80"]),
    tags:        j(["Weekend", "Nature", "Coffee", "Coorg"]),
    agenda:      j([
      { time: "Day 1 · 5:00 AM", title: "Pickup from Silk Board", speaker: "" },
      { time: "10:30 AM",        title: "Trek begins — coffee estate trail", speaker: "" },
      { time: "7:00 PM",         title: "Homestay check-in + coffee tasting", speaker: "" },
      { time: "Day 2 · 6:30 AM", title: "Sunrise hike — Mandalpatti Peak", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[3],
  },
  {
    title:       "Nandi Hills Pre-Dawn Ride & Sunrise Trek",
    description: "Cycle up to Nandi Hills and catch one of India's most spectacular sunrises over the Deccan plateau. Then hike the fort trail.\n\nCycles provided. Difficulty: Moderate. Meet at 4:00 AM at the base.",
    category:    "TREK",
    location:    "Nandi Hills, Karnataka",
    date:        daysFromNow(3),
    fee:         699,
    maxParticipants: 20,
    images:      j(["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80"]),
    tags:        j(["Cycling", "Sunrise", "Day trip"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "Kudremukh High-Altitude Trek — 3 Days",
    description: "One of Karnataka's toughest and most beautiful treks. Kudremukh Peak at 1,892m offers sweeping views of Shola forests, grasslands, and the Arabian Sea.\n\nDifficulty: Hard | Permits included | All meals & camps provided.",
    category:    "TREK",
    location:    "Kudremukh National Park, Karnataka",
    date:        daysFromNow(21),
    fee:         5999,
    maxParticipants: 12,
    images:      j(["https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&q=80"]),
    tags:        j(["3-day", "High altitude", "Karnataka", "Hard"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },

  // ── SPORTS (3) ──────────────────────────────────────────────────────────────
  {
    title:       "Corporate Cricket League — Season 4 Opening",
    description: "The biggest inter-company cricket league is back! 8 teams, 24 matches, 1 champion.\n\nRegister as a team of 11. Matches on weekends at Chinnaswamy Practice Ground. Kits, umpires, and scoring app provided. Prize pool: ₹50,000.",
    category:    "SPORTS",
    location:    "Chinnaswamy Practice Ground, Bengaluru",
    date:        daysFromNow(6),
    fee:         1499,
    maxParticipants: 120,
    images:      j(["https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=1200&q=80"]),
    tags:        j(["Cricket", "League", "Team sport"]),
    agenda:      j([
      { time: "7:00 AM",  title: "Team registration & toss", speaker: "" },
      { time: "7:30 AM",  title: "Opening ceremony", speaker: "League Commissioner" },
      { time: "8:00 AM",  title: "Match 1 — Group A", speaker: "" },
      { time: "11:00 AM", title: "Match 2 — Group B", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[1],
  },
  {
    title:       "Friday Futsal League — Weekly 5-a-side",
    description: "Drop in and play! Every Friday evening, 6v6 futsal at Phoenix Mall indoor courts. All skill levels welcome — we match teams dynamically.\n\nBring: Sports shoes (no studs), water bottle. Jerseys provided.",
    category:    "SPORTS",
    location:    "Phoenix Mall Indoor Courts, Whitefield",
    date:        daysFromNow(2),
    fee:         299,
    maxParticipants: 36,
    images:      j(["https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&q=80"]),
    tags:        j(["Football", "Weekly", "Drop-in"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[2],
  },
  {
    title:       "Badminton Tournament — Doubles Open",
    description: "32 pairs, single-elimination doubles tournament. Professional shuttle cocks provided.\n\nPrize: ₹10,000 for winners, ₹5,000 for runners-up.",
    category:    "SPORTS",
    location:    "Decathlon Badminton Arena, Sarjapur Road",
    date:        daysFromNow(10),
    fee:         799,
    maxParticipants: 64,
    images:      j(["https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=1200&q=80"]),
    tags:        j(["Badminton", "Tournament", "Doubles"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[3],
  },

  // ── MUSIC (3) ───────────────────────────────────────────────────────────────
  {
    title:       "Indie Music Night — Unplugged at Windmills Craftworks",
    description: "Three indie acts, one stage, zero auto-tune. Windmills Craftworks hosts another intimate unplugged night featuring Bengaluru's rising indie artists.\n\nLineup: Srishti & The Echoes | The Mistry Project | Arjun Mehta Solo\n\nCraft beer and food available. Doors open at 7 PM.",
    category:    "MUSIC",
    location:    "Windmills Craftworks, Whitefield",
    date:        daysFromNow(4),
    fee:         599,
    maxParticipants: 150,
    images:      j(["https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80"]),
    tags:        j(["Indie", "Live Music", "Unplugged", "Craft Beer"]),
    agenda:      j([
      { time: "7:00 PM", title: "Doors open", speaker: "" },
      { time: "7:30 PM", title: "Srishti & The Echoes", speaker: "" },
      { time: "8:15 PM", title: "The Mistry Project", speaker: "" },
      { time: "9:00 PM", title: "Arjun Mehta — solo set", speaker: "" },
      { time: "9:45 PM", title: "Open jam session", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[0],
  },
  {
    title:       "Classical Carnatic Evening — Raga Immersion",
    description: "A curated evening of Carnatic classical music in an intimate setting. Featuring vocalist Vidya Kalyanaraman accompanied by Mridangam and Violin.\n\nThe performance explores Bhairavi, Kalyani, and Shankarabharanam ragas. Pre-concert talk at 6 PM.",
    category:    "MUSIC",
    location:    "Ranga Shankara, JP Nagar",
    date:        daysFromNow(11),
    fee:         349,
    maxParticipants: 80,
    images:      j(["https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&q=80"]),
    tags:        j(["Carnatic", "Classical", "Raga", "Live"]),
    agenda:      j([
      { time: "6:00 PM", title: "Pre-concert talk: Understanding ragas", speaker: "Vidya Kalyanaraman" },
      { time: "6:45 PM", title: "Main concert — Bhairavi & Kalyani", speaker: "" },
      { time: "8:30 PM", title: "Q&A with artists", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[1],
  },
  {
    title:       "DJ Workshop — Learn to Mix & Scratch",
    description: "A 4-hour beginner workshop on DJ fundamentals: beatmatching, EQing, transitions, and scratch basics. Hands-on time on Pioneer CDJ-2000s.\n\nBring headphones. Limited to 10 participants for maximum hands-on time.",
    category:    "MUSIC",
    location:    "Furtados Music School, Koramangala",
    date:        daysFromNow(16),
    fee:         1499,
    maxParticipants: 10,
    images:      j(["https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=1200&q=80"]),
    tags:        j(["DJ", "Workshop", "Beginner", "Electronic"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[2],
  },

  // ── COMEDY / STANDUP (3) ─────────────────────────────────────────────────────
  {
    title:       "Open Mic Night — The Comedy Club Bengaluru",
    description: "Bengaluru's longest-running open mic. 20 spots, 5 minutes each. Show up, sign up, and make strangers laugh (or cringe — both are valid).\n\nAudience tickets are free. Sign up for a spot at the door from 7 PM.",
    category:    "COMEDY",
    location:    "The Comedy Club, Church Street",
    date:        daysFromNow(2),
    fee:         0,
    maxParticipants: 80,
    images:      j(["https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=1200&q=80"]),
    tags:        j(["Open Mic", "Standup", "Free", "Weekly"]),
    agenda:      j([
      { time: "7:00 PM", title: "Sign-ups & warm-up", speaker: "" },
      { time: "7:30 PM", title: "Open mic begins — 20 acts × 5 min", speaker: "" },
      { time: "9:30 PM", title: "Headliner set", speaker: "Surprise act" },
    ]),
    isBoosted:   false,
    organizerId: USERS[3],
  },
  {
    title:       "Rahul Subramanian — Live in Bengaluru",
    description: "Catch Rahul Subramanian's new hour-long special 'Hindsight' live in Bengaluru. Dry wit, corporate trauma, and extremely relatable life observations.\n\nLimited tickets — sold out at every other city. Don't wait.",
    category:    "COMEDY",
    location:    "NIMHANS Convention Centre, Bengaluru",
    date:        daysFromNow(9),
    fee:         799,
    maxParticipants: 500,
    images:      j(["https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=1200&q=80"]),
    tags:        j(["Standup", "Live Show", "Comedy Special"]),
    agenda:      j([
      { time: "6:30 PM", title: "Doors open", speaker: "" },
      { time: "7:00 PM", title: "Opening act — 15 min", speaker: "TBA" },
      { time: "7:20 PM", title: "Rahul Subramanian — 'Hindsight'", speaker: "" },
      { time: "8:30 PM", title: "Q&A & merch signing", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[4],
  },
  {
    title:       "Standup Workshop — Writing Your First 5 Minutes",
    description: "Ever wanted to try standup but didn't know where to start? This workshop covers joke structure, finding your voice, and performing your first set in a safe environment.\n\nEnds with a mini showcase for friends & family.",
    category:    "COMEDY",
    location:    "Improv Comedy Club, Indiranagar",
    date:        daysFromNow(18),
    fee:         899,
    maxParticipants: 15,
    images:      j(["https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=80"]),
    tags:        j(["Workshop", "Standup", "Beginner", "Writing"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },

  // ── FOOD (3) ─────────────────────────────────────────────────────────────────
  {
    title:       "Secret Supper Club — Japanese Omakase Edition",
    description: "A 7-course omakase dinner prepared by Chef Kenji in a secret rooftop location revealed 2 hours before the event.\n\nIngredients flown in from Tsukiji market. Sake pairing available at ₹1,500 extra. Strictly no dietary accommodations — trust the chef.",
    category:    "FOOD",
    location:    "Secret location, Central Bengaluru (revealed 2 hrs before)",
    date:        daysFromNow(7),
    fee:         3999,
    maxParticipants: 14,
    images:      j(["https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1200&q=80"]),
    tags:        j(["Japanese", "Omakase", "Fine Dining", "Secret Venue"]),
    agenda:      j([
      { time: "7:30 PM", title: "Arrival & welcome drink", speaker: "" },
      { time: "8:00 PM", title: "Course 1–3: Ocean & Nigiri", speaker: "Chef Kenji" },
      { time: "8:45 PM", title: "Course 4–5: Wagyu & Miso", speaker: "" },
      { time: "9:30 PM", title: "Course 6–7: Dessert & Matcha", speaker: "" },
    ]),
    requiresApproval: true,
    isBoosted:   true,
    organizerId: USERS[1],
  },
  {
    title:       "Bengaluru Food Walk — Frazer Town Muslim Food Trail",
    description: "Explore Frazer Town's legendary halal food scene — shawarma, biryani, Irani chai, and desserts that are practically illegal.\n\nGuided walk with food stops at 6 iconic spots. Small group, maximum eating.",
    category:    "FOOD",
    location:    "Frazer Town, Bengaluru",
    date:        daysFromNow(5),
    fee:         799,
    maxParticipants: 16,
    images:      j(["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80"]),
    tags:        j(["Food Walk", "Street Food", "Halal", "Frazer Town"]),
    agenda:      j([
      { time: "7:00 PM", title: "Meet at Frazer Town Clock Tower", speaker: "" },
      { time: "7:15 PM", title: "Stop 1: Shwarma at Al Safa", speaker: "" },
      { time: "7:45 PM", title: "Stop 2: Biryani at Zam Zam", speaker: "" },
      { time: "8:30 PM", title: "Stop 3: Irani chai & Osmania biscuits", speaker: "" },
      { time: "9:00 PM", title: "Dessert stop: Double Ka Meetha & Khubani", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[2],
  },
  {
    title:       "Home Cook Showcase — Community Potluck & Cook-off",
    description: "Bring a dish, share a recipe, meet great people. Our quarterly potluck features a friendly cook-off judged by Korpo members.\n\nCategories: Best Main, Best Dessert, Most Creative. Bring enough for 8 people.",
    category:    "FOOD",
    location:    "HSR Club House, HSR Layout",
    date:        daysFromNow(13),
    fee:         0,
    maxParticipants: 40,
    images:      j(["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80"]),
    tags:        j(["Potluck", "Cook-off", "Community", "Free"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[3],
  },

  // ── WELLNESS (3) ──────────────────────────────────────────────────────────────
  {
    title:       "Sunrise Yoga & Meditation — Lal Bagh Botanical Gardens",
    description: "Start your Sunday with a 90-minute Hatha Yoga and guided meditation session inside Lal Bagh, surrounded by century-old trees.\n\nInstructor: Meera Krishnamurthy (RYT-500, 12 years teaching). All levels welcome. Mat provided.",
    category:    "WELLNESS",
    location:    "Lal Bagh Botanical Gardens, Bengaluru",
    date:        daysFromNow(3),
    fee:         299,
    maxParticipants: 30,
    images:      j(["https://images.unsplash.com/photo-1588286840104-8957b019727f?w=1200&q=80"]),
    tags:        j(["Yoga", "Meditation", "Outdoor", "Sunday Morning"]),
    agenda:      j([
      { time: "6:00 AM", title: "Arrive & settle in", speaker: "" },
      { time: "6:15 AM", title: "Pranayama & breathwork", speaker: "Meera Krishnamurthy" },
      { time: "6:45 AM", title: "Hatha Yoga flow", speaker: "" },
      { time: "7:30 AM", title: "Guided meditation — 20 min", speaker: "" },
      { time: "7:50 AM", title: "Silent tea & sharing circle", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "Mental Health First Aid — 1-Day Certification",
    description: "A certified 8-hour Mental Health First Aid course that teaches you how to identify, understand, and respond to signs of mental illness in colleagues, friends, or family.\n\nCertification valid 3 years. Includes workbook and resource kit.",
    category:    "WELLNESS",
    location:    "The Healing Space, Koramangala",
    date:        daysFromNow(17),
    fee:         2499,
    maxParticipants: 20,
    images:      j(["https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=1200&q=80"]),
    tags:        j(["Mental Health", "Certification", "Workshop"]),
    agenda:      j([
      { time: "9:00 AM",  title: "Module 1: Recognising warning signs", speaker: "" },
      { time: "11:00 AM", title: "Module 2: Crisis intervention basics", speaker: "" },
      { time: "1:00 PM",  title: "Lunch break", speaker: "" },
      { time: "2:00 PM",  title: "Module 3: Active listening skills", speaker: "" },
      { time: "4:00 PM",  title: "Role play scenarios & debrief", speaker: "" },
      { time: "5:00 PM",  title: "Certification exam & wrap", speaker: "" },
    ]),
    requiresApproval: true,
    isBoosted:   false,
    organizerId: USERS[0],
  },
  {
    title:       "Cold Plunge & Breathwork Morning",
    description: "Wim Hof-inspired breathwork session followed by a guided cold plunge. Scientifically proven to boost dopamine, reduce stress, and improve focus.\n\nNo experience needed. Towels and warm drinks provided. Waiver required.",
    category:    "WELLNESS",
    location:    "Altitude Fitness, Indiranagar",
    date:        daysFromNow(6),
    fee:         699,
    maxParticipants: 12,
    images:      j(["https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80"]),
    tags:        j(["Cold Plunge", "Breathwork", "Wim Hof", "Morning"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[1],
  },

  // ── TECH (3) ───────────────────────────────────────────────────────────────
  {
    title:       "Build with AI — Hackathon (24 Hours)",
    description: "A 24-hour hackathon to build products using LLMs, vision models, and AI APIs. Open to all skill levels — solo or team of up to 4.\n\nPrize pool: ₹1,00,000 across 3 tracks: Consumer App, Enterprise Tool, Dev Tool.\n\nMentors from Anthropic, Google DeepMind, and Sarvam AI on-site.",
    category:    "TECH",
    location:    "NASSCOM 10,000 Startups Hub, Bengaluru",
    date:        daysFromNow(20),
    fee:         0,
    maxParticipants: 200,
    images:      j(["https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80"]),
    tags:        j(["AI", "Hackathon", "LLM", "24hr", "Free"]),
    agenda:      j([
      { time: "Day 1 · 9:00 AM", title: "Check-in, team formation & API keys", speaker: "" },
      { time: "10:00 AM",        title: "Kickoff keynote & problem statements", speaker: "Sponsors" },
      { time: "11:00 AM",        title: "Hacking begins", speaker: "" },
      { time: "Day 2 · 10:00 AM",title: "Submission deadline", speaker: "" },
      { time: "11:00 AM",        title: "Demo day — 3 min per team", speaker: "" },
      { time: "2:00 PM",         title: "Winners announced", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[2],
  },
  {
    title:       "React + Next.js Deep Dive — Full Day Workshop",
    description: "A hands-on full-day workshop covering Next.js App Router, Server Components, streaming, and edge deployment. You'll build a production-ready app from scratch.\n\nPrerequisite: Basic React knowledge. Bring your laptop.",
    category:    "TECH",
    location:    "Thoughtworks Office, Bengaluru",
    date:        daysFromNow(15),
    fee:         1999,
    maxParticipants: 30,
    images:      j(["https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80"]),
    tags:        j(["React", "Next.js", "Workshop", "Frontend"]),
    agenda:      j([
      { time: "9:00 AM",  title: "App Router fundamentals", speaker: "" },
      { time: "11:00 AM", title: "Server & Client Components deep dive", speaker: "" },
      { time: "1:00 PM",  title: "Lunch", speaker: "" },
      { time: "2:00 PM",  title: "Data fetching patterns & caching", speaker: "" },
      { time: "4:00 PM",  title: "Auth, deployment & optimisation", speaker: "" },
      { time: "5:30 PM",  title: "Q&A & networking", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[3],
  },
  {
    title:       "DevTalks BLR — Engineering at Scale",
    description: "Monthly engineering meetup. This edition: war stories from engineers who've scaled systems to millions of users.\n\nTalks from engineers at Zepto, Razorpay, and CRED. Free pizza. Strong opinions.",
    category:    "TECH",
    location:    "CRED HQ, Koramangala",
    date:        daysFromNow(11),
    fee:         0,
    maxParticipants: 100,
    images:      j(["https://images.unsplash.com/photo-1540553016722-983e48a2cd10?w=1200&q=80"]),
    tags:        j(["Engineering", "Scale", "Talks", "Free"]),
    agenda:      j([
      { time: "6:30 PM", title: "Doors open & pizza", speaker: "" },
      { time: "7:00 PM", title: "Talk: How Zepto handles 200k orders/day", speaker: "Siddharth V, Zepto" },
      { time: "7:40 PM", title: "Talk: Razorpay's payment reliability stack", speaker: "Priya N, Razorpay" },
      { time: "8:20 PM", title: "Open Q&A", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[4],
  },

  // ── WORKSHOP (3) ─────────────────────────────────────────────────────────────
  {
    title:       "Leather Craft Workshop — Make Your Own Wallet",
    description: "In this 3-hour beginner workshop you'll hand-stitch a full-grain leather bifold wallet using traditional saddle-stitch technique.\n\nAll tools, leather, and thread provided. Take your wallet home. No experience needed.",
    category:    "WORKSHOP",
    location:    "The Maker's Corner, Indiranagar",
    date:        daysFromNow(8),
    fee:         1299,
    maxParticipants: 10,
    images:      j(["https://images.unsplash.com/photo-1473188588951-666fce8e7c68?w=1200&q=80"]),
    tags:        j(["Leather", "Craft", "DIY", "Beginner"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },
  {
    title:       "Candle Making Masterclass — Soy & Beeswax",
    description: "Learn to make premium hand-poured candles using soy wax and beeswax. Cover fragrance blending, wick selection, and container prep.\n\nLeave with 4 finished candles and the knowledge to make more at home.",
    category:    "WORKSHOP",
    location:    "Studio Bloom, HSR Layout",
    date:        daysFromNow(13),
    fee:         999,
    maxParticipants: 12,
    images:      j(["https://images.unsplash.com/photo-1602178980988-a4a0c020d82e?w=1200&q=80"]),
    tags:        j(["Candles", "DIY", "Fragrance", "Weekend"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[1],
  },
  {
    title:       "Public Speaking Bootcamp — 1-Day Intensive",
    description: "Transform your presentation style in one day. Covers structure, voice modulation, handling nerves, and storytelling for business.\n\nIncludes 3 recorded practice rounds with feedback. Ideal for professionals and founders.",
    category:    "WORKSHOP",
    location:    "Toastmasters Hub, MG Road",
    date:        daysFromNow(19),
    fee:         1799,
    maxParticipants: 15,
    images:      j(["https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&q=80"]),
    tags:        j(["Public Speaking", "Communication", "Career", "Bootcamp"]),
    agenda:      j([
      { time: "9:00 AM",  title: "Module 1: Structure & storytelling", speaker: "" },
      { time: "11:00 AM", title: "Practice round 1 — 3 min speech", speaker: "" },
      { time: "1:00 PM",  title: "Lunch", speaker: "" },
      { time: "2:00 PM",  title: "Module 2: Voice, body language & presence", speaker: "" },
      { time: "4:00 PM",  title: "Final showcase — 5 min each", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[2],
  },

  // ── GAMING (3) ───────────────────────────────────────────────────────────────
  {
    title:       "Valorant LAN Tournament — Solo Queue Edition",
    description: "32-player single-elimination Valorant tournament on high-end PCs at Hyper Gaming Arena. Rank up to Diamond+ to enter the invite bracket.\n\nPrize: ₹15,000 for 1st, ₹7,000 for 2nd, ₹3,000 for 3rd. All setups: 165Hz + low-latency.",
    category:    "GAMING",
    location:    "Hyper Gaming Arena, Koramangala",
    date:        daysFromNow(7),
    fee:         499,
    maxParticipants: 32,
    images:      j(["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&q=80"]),
    tags:        j(["Valorant", "FPS", "Tournament", "LAN"]),
    agenda:      j([
      { time: "10:00 AM", title: "Check-in & seeding matches", speaker: "" },
      { time: "11:00 AM", title: "Round of 32", speaker: "" },
      { time: "2:00 PM",  title: "Round of 16 & Quarterfinals", speaker: "" },
      { time: "5:00 PM",  title: "Semifinals", speaker: "" },
      { time: "7:00 PM",  title: "Grand final + trophy ceremony", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[3],
  },
  {
    title:       "Board Game Café Night — Eurogames Edition",
    description: "Join us for a curated evening of heavy Eurogames at Bengaluru's best board game café. This month: Brass Birmingham, Terraforming Mars, and Through the Ages.\n\nTeach sessions at 6 PM for each game. Solo or groups of 2–4 welcome.",
    category:    "GAMING",
    location:    "Dice & Dine Café, Indiranagar",
    date:        daysFromNow(10),
    fee:         299,
    maxParticipants: 24,
    images:      j(["https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=1200&q=80"]),
    tags:        j(["Board Games", "Eurogames", "Evening", "Café"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "Retro Gaming Marathon — SNES, N64 & Dreamcast",
    description: "Pull up a beanbag and play your childhood games on original hardware. CRTs, cartridges, and controllers — the full authentic experience.\n\nFeatured games: Mario Kart 64, GoldenEye, Street Fighter II, Sonic Adventure. Free to play.",
    category:    "GAMING",
    location:    "Geek Haven, Jayanagar",
    date:        daysFromNow(4),
    fee:         199,
    maxParticipants: 50,
    images:      j(["https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80"]),
    tags:        j(["Retro", "Nintendo", "Nostalgia", "Arcade"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },

  // ── MOVIE (3) ────────────────────────────────────────────────────────────────
  {
    title:       "Rooftop Cinema — Cult Classics Night: Blade Runner 2049",
    description: "Watch Denis Villeneuve's masterpiece under the stars on our rooftop with a 4K projector and premium sound.\n\nDeck chairs, blankets, and popcorn included. Bar open from 7 PM. Rain contingency: indoor backup screen.",
    category:    "MOVIE",
    location:    "The Skyline Rooftop, UB City",
    date:        daysFromNow(5),
    fee:         699,
    maxParticipants: 60,
    images:      j(["https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&q=80"]),
    tags:        j(["Rooftop", "Sci-Fi", "Cult Classic", "Outdoor Cinema"]),
    agenda:      j([
      { time: "7:00 PM", title: "Bar opens — welcome drinks", speaker: "" },
      { time: "7:30 PM", title: "Short film: 'Sunspring' (AI-written)", speaker: "" },
      { time: "7:50 PM", title: "Blade Runner 2049 (163 min)", speaker: "" },
      { time: "10:35 PM", title: "Post-film discussion", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[1],
  },
  {
    title:       "Indian Cinema Rewind — Gulzar Retrospective",
    description: "A curated screening of three Gulzar directorial classics: Aandhi (1975), Mausam (1975), and Ijaazat (1987), with English subtitles.\n\nOpening talk on Gulzar's poetry and cinema by film critic Sudhish Kamath.",
    category:    "MOVIE",
    location:    "Suchitra Film Society, Bengaluru",
    date:        daysFromNow(14),
    fee:         249,
    maxParticipants: 120,
    images:      j(["https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&q=80"]),
    tags:        j(["Indian Cinema", "Classic", "Gulzar", "Film Society"]),
    agenda:      j([
      { time: "4:00 PM", title: "Opening talk: Gulzar — the poet-director", speaker: "Sudhish Kamath" },
      { time: "4:45 PM", title: "Screening: Aandhi (1975)", speaker: "" },
      { time: "7:00 PM", title: "Break & chai", speaker: "" },
      { time: "7:30 PM", title: "Screening: Ijaazat (1987)", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[2],
  },
  {
    title:       "Screenplay Workshop — From Idea to Scene",
    description: "A 3-hour screenwriting workshop focused on the first 10 pages — the most important pages of any script.\n\nCover loglines, character wants vs. needs, and scene construction. Participants pitch their ideas and get group feedback.",
    category:    "MOVIE",
    location:    "Film Collective Studio, Jayanagar",
    date:        daysFromNow(22),
    fee:         799,
    maxParticipants: 16,
    images:      j(["https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80"]),
    tags:        j(["Screenwriting", "Filmmaking", "Workshop", "Creative"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[3],
  },

  // ── FITNESS (3) ──────────────────────────────────────────────────────────────
  {
    title:       "5K Fun Run — Bengaluru Midnight Edition",
    description: "A non-competitive 5K run through the empty streets of Bengaluru at midnight. No timings, no pressure — just good vibes and bad decisions.\n\nPost-run: hot chai and Maggi at the finish line. T-shirt included in entry.",
    category:    "FITNESS",
    location:    "Cubbon Park Start Line, Bengaluru",
    date:        daysFromNow(9),
    fee:         499,
    maxParticipants: 200,
    images:      j(["https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=1200&q=80"]),
    tags:        j(["Running", "5K", "Night Run", "Fun"]),
    agenda:      j([
      { time: "11:30 PM", title: "Assembly & bib collection", speaker: "" },
      { time: "12:00 AM", title: "Run begins", speaker: "" },
      { time: "1:00 AM",  title: "Finish line — chai & Maggi", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "CrossFit Open Community WOD",
    description: "Drop into this community CrossFit workout — no membership required. We'll run through the CrossFit Open WOD 24.1 with scaled options for every fitness level.\n\nCoach-led. Chalk, equipment, and post-WOD protein shake provided.",
    category:    "FITNESS",
    location:    "CrossFit Bengaluru, HSR Layout",
    date:        daysFromNow(4),
    fee:         0,
    maxParticipants: 40,
    images:      j(["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80"]),
    tags:        j(["CrossFit", "HIIT", "Free", "Community"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },
  {
    title:       "Marathon Training Programme — 12 Weeks to 42K",
    description: "Structured 12-week marathon training programme for runners targeting the Bengaluru Marathon. Weekly group runs on Sunday mornings + 2 weekday sessions.\n\nCoach: Ravi Shankar (6× marathon finisher, certified running coach). GPS watch rental available.",
    category:    "FITNESS",
    location:    "Kanteerava Stadium, Bengaluru",
    date:        daysFromNow(7),
    fee:         2999,
    maxParticipants: 25,
    images:      j(["https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=1200&q=80"]),
    tags:        j(["Marathon", "Running", "Training", "12-week"]),
    agenda:      null,
    isBoosted:   true,
    organizerId: USERS[1],
  },

  // ── HOBBY (3) ─────────────────────────────────────────────────────────────────
  {
    title:       "Urban Sketch Walk — Cubbon Park Edition",
    description: "Grab your sketchbook and spend a Sunday morning drawing the trees, pavilions, and people of Cubbon Park. Guided by professional illustrator Preethi Rao.\n\nAll skill levels welcome. Materials provided for first-timers.",
    category:    "HOBBY",
    location:    "Cubbon Park Main Gate, Bengaluru",
    date:        daysFromNow(4),
    fee:         399,
    maxParticipants: 16,
    images:      j(["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80"]),
    tags:        j(["Art", "Sketching", "Outdoor", "Sunday"]),
    agenda:      j([
      { time: "8:30 AM", title: "Meet at main gate, intro & warm-up", speaker: "Preethi Rao" },
      { time: "9:00 AM", title: "Sketch session 1 — Architecture & trees", speaker: "" },
      { time: "10:30 AM", title: "Sketch session 2 — People & movement", speaker: "" },
      { time: "11:30 AM", title: "Group critique & chai", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "Pottery Workshop — Wheel Throwing for Beginners",
    description: "3-hour hands-on pottery session. Learn to centre clay, pull walls, and shape a bowl on the wheel, guided by ceramic artist Lakshmi N.\n\nTake your dried piece home after a week. All materials and apron provided.",
    category:    "HOBBY",
    location:    "Clay Collective Studio, HSR Layout",
    date:        daysFromNow(15),
    fee:         1299,
    maxParticipants: 8,
    images:      j(["https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&q=80"]),
    tags:        j(["Pottery", "Creative", "Beginner"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[2],
  },
  {
    title:       "Amateur Photography Walk — Street Stories",
    description: "A guided photo walk through the streets of Shivajinagar market — one of Bengaluru's most photogenic neighbourhoods.\n\nTheme: People, colour, and commerce. Debrief and image review at a nearby cafe.",
    category:    "HOBBY",
    location:    "Shivajinagar Market, Bengaluru",
    date:        daysFromNow(7),
    fee:         0,
    maxParticipants: 20,
    images:      j(["https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1200&q=80"]),
    tags:        j(["Photography", "Street", "Free"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },

  // ── TRAVEL (3) ───────────────────────────────────────────────────────────────
  {
    title:       "Hampi Heritage Trip — 3 Days with Historians",
    description: "Explore the ruins of the Vijayanagara Empire with historian guides. Hampi is a UNESCO World Heritage Site and arguably the most dramatic landscape in India.\n\nIncludes: Bus from Bengaluru, heritage guide, guesthouse, all breakfasts.",
    category:    "TRAVEL",
    location:    "Hampi, Karnataka (Pickup: Bengaluru)",
    date:        daysFromNow(25),
    fee:         4999,
    maxParticipants: 16,
    images:      j(["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&q=80"]),
    tags:        j(["Heritage", "History", "Weekend", "Karnataka"]),
    agenda:      j([
      { time: "Day 1 · 9:00 PM", title: "Overnight sleeper bus from Bengaluru", speaker: "" },
      { time: "Day 2 · 6:00 AM", title: "Arrival, check-in & sunrise at Matanga Hill", speaker: "" },
      { time: "9:00 AM",         title: "Full-day Hampi heritage walk", speaker: "Historian guide" },
      { time: "Day 3 · 8:00 AM", title: "Tungabhadra river coracle ride", speaker: "" },
      { time: "2:00 PM",         title: "Return bus to Bengaluru", speaker: "" },
    ]),
    isBoosted:   true,
    organizerId: USERS[3],
  },
  {
    title:       "Chikmagalur Coffee & Camping Weekend",
    description: "2 nights camping in the coffee hills of Chikmagalur. Morning plantation walks, bonfire evenings, stargazing, and very good coffee.\n\nAll camping gear provided. Vegetarian meals included. Max 16 people for an intimate experience.",
    category:    "TRAVEL",
    location:    "Chikmagalur, Karnataka",
    date:        daysFromNow(18),
    fee:         3299,
    maxParticipants: 16,
    images:      j(["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80"]),
    tags:        j(["Camping", "Coffee", "Nature", "Chikmagalur"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[4],
  },
  {
    title:       "Gokarna Beach & Temple Solo Travel Meetup",
    description: "A meetup for solo travellers heading to Gokarna. We coordinate transport, accommodation, and itinerary — you show up and make friends.\n\nCovered: Om Beach, Half Moon Beach, Mahabaleshwar temple, sunset cliff.",
    category:    "TRAVEL",
    location:    "Gokarna, Karnataka",
    date:        daysFromNow(30),
    fee:         1999,
    maxParticipants: 20,
    images:      j(["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80"]),
    tags:        j(["Solo Travel", "Beach", "Gokarna", "Meetup"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[0],
  },

  // ── OTHER (2) ────────────────────────────────────────────────────────────────
  {
    title:       "Flea Market & Garage Sale — Korpo Community Edition",
    description: "Buy, sell, and swap with your colleagues. Bring anything you no longer need — clothes, books, gadgets, furniture, plants.\n\nFree stall for every seller (max 1 table). No commission taken. 100% peer-to-peer.",
    category:    "OTHER",
    location:    "EcoWorld Terrace, Bellandur",
    date:        daysFromNow(11),
    fee:         0,
    maxParticipants: 200,
    images:      j(["https://images.unsplash.com/photo-1530062845289-9109b2c9c868?w=1200&q=80"]),
    tags:        j(["Flea Market", "Buy & Sell", "Community", "Free"]),
    agenda:      null,
    isBoosted:   false,
    organizerId: USERS[1],
  },
  {
    title:       "Korpo Volunteer Day — City Cleanup Drive",
    description: "Join fellow Korpo members for a morning of cleaning and greening Cubbon Park. Gloves, bags, and saplings provided by BBMP in partnership with Korpo.\n\nPost-drive breakfast at MTR sponsored by Korpo. Certificate of participation issued.",
    category:    "OTHER",
    location:    "Cubbon Park, Bengaluru",
    date:        daysFromNow(6),
    fee:         0,
    maxParticipants: 100,
    images:      j(["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80"]),
    tags:        j(["Volunteer", "Community", "Environment", "Free"]),
    agenda:      j([
      { time: "7:00 AM", title: "Assembly & kit distribution", speaker: "" },
      { time: "7:30 AM", title: "Zone assignments & cleanup begins", speaker: "" },
      { time: "9:30 AM", title: "Sapling planting session", speaker: "" },
      { time: "10:30 AM", title: "Group photo & certificate distribution", speaker: "" },
      { time: "11:00 AM", title: "Breakfast at MTR (sponsored)", speaker: "" },
    ]),
    isBoosted:   false,
    organizerId: USERS[2],
  },
]

console.log("Clearing existing events and RSVPs…")
await db.execute("DELETE FROM EventRsvp")
await db.execute("DELETE FROM Event")
console.log("✓ Cleared\n")

console.log(`Seeding ${EVENTS.length} events across all categories…\n`)
let inserted = 0

for (const e of EVENTS) {
  const eid = id()
  const now = new Date().toISOString()
  try {
    await db.execute({
      sql: `INSERT INTO Event (
        id, organizerId, title, description, category,
        date, location, maxParticipants, fee, images,
        isActive, agenda, onlineLink, tags, isBoosted,
        requiresApproval, createdAt, updatedAt
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, NULL, ?, ?, ?, ?, ?)`,
      args: [
        eid, e.organizerId, e.title, e.description, e.category,
        e.date, e.location, e.maxParticipants ?? null, e.fee, e.images,
        e.agenda ?? null, e.tags,
        e.isBoosted ? 1 : 0,
        e.requiresApproval ? 1 : 0,
        now, now,
      ],
    })

    const rsvpers  = USERS.filter(u => u !== e.organizerId)
    const count    = 2 + Math.floor(Math.random() * (rsvpers.length - 1))
    const shuffled = [...rsvpers].sort(() => Math.random() - 0.5).slice(0, count)
    for (const userId of shuffled) {
      const rid = "rsvp_" + Date.now() + "_" + Math.random().toString(36).slice(2, 7)
      await db.execute({
        sql:  "INSERT OR IGNORE INTO EventRsvp (id, eventId, userId, createdAt) VALUES (?, ?, ?, ?)",
        args: [rid, eid, userId, now],
      })
    }

    console.log(`  ✓ [${e.category.padEnd(10)}] ${e.title.slice(0, 55)}`)
    inserted++
  } catch (err) {
    console.error(`  ✗ [${e.category}] ${e.title.slice(0, 40)}: ${err.message}`)
  }
}

const catCounts = {}
for (const e of EVENTS) catCounts[e.category] = (catCounts[e.category] ?? 0) + 1

console.log(`\n✓ Done — ${inserted}/${EVENTS.length} events seeded.\n`)
console.log("Category breakdown:")
for (const [cat, count] of Object.entries(catCounts))
  console.log(`  ${cat.padEnd(12)} ${count} event${count > 1 ? "s" : ""}`)
console.log()
process.exit(0)
